### PR TITLE
[lnurl]: support for pay to lnurl

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Open to feedback.

Created a new command called lnurl.
Added support for lnurl pay.

Decodes a bech32 string which reveals a url, fetching this url returns a callback url.
Fetching the call back url with an amount returns a bolt 11 payreq.

New directory: lnurl

New files:
lnurl/index.js
lnurl/pay.js

Files changed:
bos
commands/constants.json

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
> how to test this? I don't know about a testnet service that supports lnurl

Can you try this website?

https://lnurl-toolbox.degreesofzero.com/

You can use this for mainnet
https://lnurl.fiatjaf.com/

**Comment by alexbosworth** [comment]
I think both sites are mainnet only

**Comment by niteshbalusu11** [comment]
> I think both sites are mainnet only

The first one does not transact any funds. I guess it generates fake invoices or something.

**Comment by alexbosworth** [comment]
weird ok I guess I can test it not doing anything lol

**Comment by alexbosworth** [comment]
it was merged but I had to rebase

**Pull request closed without merging**
