### PR TITLE
[inbound-channel-rules]: Add support for rejecting tor only peers

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

Added a new forumla variable `clearnet` to reject channels from tor only peers in the `inbound-channel-rules` command.

Closes: #484 

Files changed:
bos
peers/detect_open_rule_violation
peers/intercept_inbound_channels
peers/open_request_violation

### CODE REVIEW

**Comment by alexbosworth** [comment]
what about the intent to block people who have ANY Tor address? maybe there should be two variables?

- HAS_TOR_ADDRESS
- HAS_CLEARNET_ADDRESS

**Comment by niteshbalusu11** [comment]
Then we need 3 variables I guess? Because you could have Tor and Clearnet. 
so IS_TOR_ONLY, HAS_TOR, HAS_CLEARNET ?

**Comment by alexbosworth** [comment]
well formulas can do conditions so if you want tor only then you could do has_tor && !has_clearnet

**Comment by niteshbalusu11** [comment]
How do we write that?
`--rule="has_tor_address && !has_clearnet_address"` and `--rule="AND(has_tor_address, !has_clearnet_address)"` don't work. Looks like it doesn't like the `!` operator.

**Comment by alexbosworth** [comment]
Good question, did you try the NOT() function?

**Comment by niteshbalusu11** [comment]
Ok looks like NOT() works.

**Comment by alexbosworth** [comment]
maybe CLEARNET and TOR are ok variable names, so then like NOT(TOR) would reject any node that had a TOR address?

**Comment by niteshbalusu11** [comment]
> maybe CLEARNET and TOR are ok variable names, so then like NOT(TOR) would reject any node that had a TOR address?

Made changes to make it work like this. `NOT(TOR)` rejects all TOR peers. To accept peers that support TOR and CLEARNET, this seems to be working `--rule="AND(clearnet, NOT(TOR))"`

**Comment by alexbosworth** [comment]
Cool, why would you specify not(tor) to accept peers that support tor though?

tor equates to is_advertising_tor_address and clearnet equates to is_advertising_clearnet_address right?

**Comment by niteshbalusu11** [comment]
Yeah, that's what I meant. Just accept or reject channels based on what they are advertising.

**Comment by alexbosworth** [comment]
ok sounds good

**Pull request merged**
