### PR TITLE
Add summary to graph command output

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Graph command logs the summary today, I made it a return value which outputs as a table as it would be helpful for me to get the summary output via Rest API.

Please let me know what you think.

Files changed:
bos
network/get_graph_entry.js

### CODE REVIEW

**Comment by alexbosworth** [comment]
is there another way to do it? the output looks weird for `bos graph` to show the summary values in a one row table

**Comment by niteshbalusu11** [comment]
The return object can do only one type, correct? It can’t do both table and json logger?

**Comment by alexbosworth** [comment]
Yeah I guess that is why I put the logger inside that method

**Comment by niteshbalusu11** [comment]
Will have to think how to do this then.

**Comment by alexbosworth** [comment]
You could abstract the method out so that there are two methods, one returns the values, the other just calls and logs, then you call the value returning one if you want the values

**Comment by niteshbalusu11** [comment]
Should I make that change within bos or do that on my end?

**Comment by alexbosworth** [comment]
ah there is another issue I see which is that I want the general node details to log out first because the graph takes a long time, maybe it's better to override the logger method to get the data you want?

**Comment by niteshbalusu11** [comment]
Cool. I can do that.

**Comment by alexbosworth** [comment]
Another option is restructure the method into an event emitter and emit the node details first

**Comment by niteshbalusu11** [comment]
Yeah I could do it like how I did for rebalance and send commands with the event emitter.

**Pull request closed without merging**
