### PR TITLE
set bos directory to an env variable

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Set the bos directory to an env variable OR .bos (default) and replaced the hard coded value everywhere I found.

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
Will have to change the path joining lines everywhere in the code, since it won't be `join(homedir(), home, config.json)` etc anymore. Is that ok?

**Comment by alexbosworth** [comment]
I think it can still do join, but instead of join(homedir(), home, file) it would be join(homePath({}), file)? and homepath is going to return either the env var path or join(homedir(), home)

**Comment by niteshbalusu11** [comment]
Right yeah. Will make the changes tomorrow.

**Comment by niteshbalusu11** [comment]
Can you check now?

**Comment by alexbosworth** [comment]
I merged it but made some conflicting changes

**Pull request closed without merging**
