### PR TITLE
[chart-payments-received]: Start and end dates for chart-payments-received

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Added start and end flags for chart-payments-received to get payments for a range of dates. Start and end flags take YYYY-MM-DD format.

Files changed:
bos
get_received_chart.js

### CODE REVIEW

**Comment by alexbosworth** [comment]
what happens if days are defined and also a date range, but these values conflict

**Comment by niteshbalusu11** [comment]
If dates are defined, days is just ignored.

**Comment by alexbosworth** [comment]
if days are ignored i think it should be invalid as an argument

**Comment by niteshbalusu11** [comment]
Fixed it.

**Pull request merged**
