### PR TITLE
adding trade-secret to telegram bot

### PR DESCRIPTION
**Pull request by niteshbalusu11**
I did not make any changes to paid-services or ln-telegram repo, added the files to bos repo, they can be moved to ln-telegram.

modified files:
1. start_telegram_bot
2. create_trade (new file)
3. handle_trade_route (new file)

Most code has been copy-pasted from the paid-services repo and functions were directly called.

### CODE REVIEW

**Comment by alexbosworth** [comment]
I like the buttons and the interactiveness concepts

The high level features here are:

1. Create an invoice wrapped in a trade-secret
2. Decode the invoice wrapped in the trade secret

The flow I'm thinking about is like

Seller inputs: description of product, price of product, secret payload - they get a way to share the trade
Buyer inputs: shared thing - it shows the description, price, and shows the payreq to pay or asks if the payment was made already and it can decode the secret

This flow requires an additional change to the trade-secret system to allow for open-ended trade secrets where you don't have to specify the peer up-front, I think that part can be done with p2p communication

**Comment by niteshbalusu11** [comment]
Hey Alex - need some help when you find time with asyncjs, i got until decoding an open trade and presenting as buttons. now the last step would be picking the button and getting the invoice. I am unable to pass the decoded json that contains ID's and descriptions and the `to` pubkey of the node that's selling trades from handle_trade_route and find_trade back to start_telegram_bot page. I have no choice but to send them back to the home page because telegram does not allow you to register a listener within a listener.

1.  Need to pass `to` function result from `find_trade.js` to `start_telegram_bot.js` and replace over here:
```
            try {
              const x = await requestTradeById({
                lnd: savedNode.lnd,
                id: clickedButton,
                to: '02ba1f14be6333e0f014c8809134bf16a7cad9cec6341f736767660e61b61733bd',
              });
              console.log(x);
            } catch(err) {
              logger.error({err});
            }
```

2. Need to pass the result of `handlePurchaseTradeRoute` in `handle_trade_route.js` to `start_telegram_bot.js`
This section results in the list of openTrades one can buy.

```
            const openTrades = await findTrade({
              lnd: lnd.lnd,
              logger,
              id: details.connect.id,
              identity: getIdentity.public_key,
              nodes: details.connect.nodes,
            });
```

**Comment by alexbosworth** [comment]
Maybe instead of trying to pass upwards, just pass the context you need to the function to begin with? There is a lot of stuff going on so it's hard for me to really grok what is relevant but like if you get the trade by its id and you want to show it, you can post to the bot directly if you give the telegram key etc to the function that was getting the trade by its id

**Comment by niteshbalusu11** [comment]
> Maybe instead of trying to pass upwards, just pass the context you need to the function to begin with? There is a lot of stuff going on so it's hard for me to really grok what is relevant but like if you get the trade by its id and you want to show it, you can post to the bot directly if you give the telegram key etc to the function that was getting the trade by its id

ok, I think I understood what you mean. I'll give that a try.

**Comment by alexbosworth** [comment]
I added a new framework for bot buttons to ln-telegram, I think this can be a model for how to merge in trade-secret

A scenario I'm interested in is one where the user is pushed a trade-secret via keysend.

Like someone pushes me a trade-secret to advertise a paid telegram group:

[My node gets a keysend with an open trade-secret and a message describing what they are offering]
- I see a new message show up with an encoded trade and a button to view the trade
- I click view, it connects and it shows me the description and price, with an encoded payment request
- I pay the payment request with bos pay and the message changes to reveal the secret, trade complete

So:
- New message: "Hey, want to join a private bos telegram group? - from yalls.org 02342 <VIEW TRADE>"
- "1 time-limited invite to private bos telegram group - 0.00001000 <PAYREQ>"
- You purchased "1 time limited invite to private bos telegram group": link://path/to/link

If you got the open trade out of band or a direct trade secret, it would skip to step 2

**Comment by niteshbalusu11** [comment]
Nice. One of the things I was thinking was, it'll be nice to add the trade quantity encoded in the message and also the bot/CLI asks for the trade quantity when creating the trade and the same number of listeners kick off directly. 

It'll be nice when it can get integrated with bos advertise, where you can say I'm selling 5 invites to private bos group.

**Comment by alexbosworth** [comment]
I added some of this stuff in the buttons model and I think that is working pretty well

Remaining aspects that I'm thinking about for end-to-end trade-secret:

1. Add a price adjustment button
2. Create a /sell-trade-secret <price> <secret> command to put up a new trade secret
3. Add a /trade-secrets command to list out open sales

After that I think the next phase is more along the lines of making them more interesting to use since you have the baseline functionality there for creation and updating

**Comment by niteshbalusu11** [comment]
Cool, price adjustment and listing open trades would be really nice.

**Pull request closed without merging**
