### PR TITLE
switch from v1 to v2 markdown

### PR DESCRIPTION
**Pull request by niteshbalusu11**
switching from v1 to v2 markdown.
In escaping I removed `*` since that isn't necessary.

### CODE REVIEW

**Comment by alexbosworth** [comment]
I think escape should be done on the ln-telegram side

**Comment by niteshbalusu11** [comment]
Ok will make that change, just read your comment on the closed PR. Do you want to pass ctx to ln-telegram and do ctx.reply there?

**Comment by alexbosworth** [comment]
I think either pass ctx or just pass the reply method and do the escaping of the message on the telegram side, another option is reply passed to ln-telegram would take 2 arguments: message and options

I tried passing ctx and it is a can of worms because checkAccess requires reply

**Comment by niteshbalusu11** [comment]
Please check now, this and the telegram repo.

**Pull request merged**
