### PR TITLE
add parse amount for increase-inbound-liquidity command

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Added parsing of amount for increase-inbound-liquidity command.

Files changed:

- bos

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
https://github.com/alexbosworth/balanceofsatoshis/issues/185

**Comment by niteshbalusu11** [comment]
Oops. There is a mistake in this. I'll have to change it.

**Comment by alexbosworth** [comment]
what's the mistake? i can fix it

**Comment by niteshbalusu11** [comment]
Fixed now.

**Comment by alexbosworth** [comment]
ah double tokens, I changed that in the merge

**Pull request closed without merging**
